### ISSUE TITLE
Generator example with TCPDF createPDF type

### ISSUE THREAD

**Issue by davidromani** [orkestra/OrkestraPdfBundle#2]
Hello again,

For now I can generate an invoice entity to PDF with the wkpdf type, but I need to see how can I use the TCPDF library because I need a very customized PDF output. It's possible?

I don't understand very well how can I use TCPDF library because it's based on PHP functions and your bundle generates an output based on a Twig template.

Kind regards,

**Comment by tyler-sommer** [comment]
I've added a TCPDF example to the README. Take a look and feel free to provide feedback.

Thanks again!

**Comment by davidromani** [comment]
Well done! I follow new instructions and now I understand how it works.
